### ISSUE TITLE
Override not working in ModuleTemplate

### ISSUE THREAD

**Issue by zralt** [kyma-project/lifecycle-manager#685] opened 2023-06-19 13:17 UTC
**Description**

I've been trying to test out lifecycle-manager, using this guide:
https://github.com/kyma-project/lifecycle-manager/blob/main/docs/developer-tutorials/local-test-setup.md

There's the step 5 where you actually create the module with the kyma cli, and upload it to the container:
```
kyma alpha create module -p ../template-operator --version 1.2.3 \
--registry k3d-registry.localhost:5111 --insecure
```

This does what it says, it creates this special OCI container and uploads it to the local registry, meanwhile also setting the baseUrl inside the module to that k3d-registry.localhost:5111 . 

Now this also generates a template.yaml, where I need to modify the baseUrl so that it can be fetched from inside the cluster where the registry is listening on port :5000 . 

The docs says that I should just rewrite the template.yaml accordingly, but this doesn't work, there are errors that the module cannot be synced because it's still trying to access the registry at port :5111.

**Expected result**

The generated "template.yaml" overrides the value in the module that's uploaded to the OCI registry. At least I assume it should work this way, since the "template.yaml" and the module yaml that's uploaded to the registry is the same.

**Actual result**

No matter what I do, it tries to sync against port :5111.

**Steps to reproduce**

Follow the guide linked.

**Troubleshooting**

I verified that module installation does work if I use an external repository. I tried to adjust the parameters of the ModuleTemplate, but it didn't help.

**Comment by lindnerby** [comment] 2023-11-06 08:13
Closing this since it's not reproducible anymore.

**Closed by lindnerby** 2023-11-06 08:13 UTC
