### ISSUE TITLE
Feature: Possibility to have overrides for single or multiple runtimes

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/lifecycle-manager#306] opened 2022-11-08 09:33 UTC
As developers while debugging issues on Production runtimes, we might want to enable particular overrides for a given runtime. An example could be we want to have debug logs enabled on our module for extended period of time so that we can better analyse the issue (as the issue might happen randomly).

We should have the ability to enable settings via overrides through our module operator on a designated single or multiple runtimes.

**Comment by jakobmoellersap** [comment] 2022-11-08 11:58
Where would you want these overrides reconciled to your module from lifecycle manager? 

Since I am assuming that you want to debug your own operator, you can do this by introducing a debug setting in the corresponding ModuleCR and enabling this flag per runtime. 

We do not plan to support specifying custom overrides for reconciliation of the runtime. The reason for this is mainly that you can simply do the override as described above in the ModuleCR and disable reconciliation for the runtime temporarily to not have your setting overwritten forcefully. We prefer this way since otherwise you would have to continously interpret and pass all override configurations into the Runtime during rendering and rerender your chart, which would affect performance since we cannot cache the finalized manifest.

For the passing of debug log options for central operators, there is #79 which takes care of passing a flag downstream to the module-operators. we wanted to implement this by label. This is a special requirement because we already know this is a centrally orchestrated flag that is independent of module implementation.

Let me know if you have further questions, otherwise feel free to close or create follow-ups.

**Comment by janmedrek** [comment] 2022-11-22 13:42
Since there are no comments I am closing this one as a duplicate of: https://github.com/kyma-project/lifecycle-manager/issues/79

**Closed by janmedrek** 2022-11-22 13:42 UTC
