### ISSUE TITLE
When Kyma resource is under deletion let module's CR know about that

### ISSUE THREAD

**Issue by PK85** [kyma-project/lifecycle-manager#430] opened 2023-02-28 07:59 UTC
**Description**

This is an additional feature for modules being deleted by the Lifecycle Manager. The LM should mark module CR with the label before calling the delete operation.
 
**Reason**

Some modules could want to act like "force-delete" when de-provisioning comes from Kyma deletion. For example, BTP Manager will delete all instances and bindings in such a scenario.

This is an optional functionality for module owners. The module does not need to react to that.

**Proposal**

- 1) Mark all modules with the standard known label, or
- 2) Allow the module owner to define a label name for LM that will be used then

**AC**

- [ ] 1) Document and implement the above feature

**Comment by jakobmoellersap** [comment] 2023-03-10 13:35
We have internally analysed the issue and come to the following conclusions / recommendations based on the use case:

We assume that we wait for all modules to be removed and block the kyma deletion with a finaliser until the (optionally given) timeout is reached. This will not change.

It assumes triggering a Delete of the kyma with `kubectl delete kyma NAME --cascade='foreground' and blocking.
Alternatively, one can use `kubectl delete kyma NAM` and we will use `background` cascading policy, which will require a regular check of the resource for it being already deleted. If it is gone, the deletion was successful.

After the timeout is reached (via kubectl through `--timeout=30s`), if not all resources are removed, one has to either manually check the Manifest Custom Resource and then decide wether finaliser removal is acceptable or not: if finaliser removal is acceptable, one can force-remove the finaliser which triggers an immediate removal of the Module from the Tracking.
   
In any case, as soon as the Kyma resource is triggered for deletion, modules will be notified by having their `deletionTimestamp` set as well, to which controllers can react. The default behaviour here MUST block by not removing a finaliser until all dependencies created by the CustomResource are removed without exception to comply with Kubernetes standards.

If the module should not wait for dependencies (e.g. to keep externally created instances), we recommend to rethink your strategy. Usually this should be done only if triggered with a deletionPropagationPolicy of `orphan`. Every other value should be respected as is.

For your concrete use case we recommend to
1. Always remove all services / instances created through the CR by blocking with a finaliser and listening for the `deletionTimestamp`
2. Document scenarios in which the finaliser can get stuck and how to deal with these scenarios
3. Do not introduce specific logic for deletion cases, instead implement only this strategy that removes all dependant objects.
4. If the cluster is completely uninstalled (kyma CR is triggered for deletion), act as if it were a normal deletion of the module and cleanup all instances created by your CR.
5. If you have a use case where you want to keep your third-party resources after the CR that triggered their creation was deleted, introduce your own `.spec` policy for this, e.g. `CleanupPolicy` with values `Orphan` and `Foreground` to map it to the correct Kubernetes primitive. This is strongly discouraged if not absolutely necessary. Instruct your users on how to use this Policy for non-default behaviour. Initialise the Policy in the default data for the Module if necessary.

If the module needs to be aware of when the Kyma resource cleans up the entire cluster (e.g. for different code paths), lifecycle manager should not introduce a custom label on our controller as it makes it implementation specific how controllers can react.

**Comment by PK85** [comment] 2023-03-13 21:23
@jakobmoellersap Just to make sure I understand it correctly. 

You mean that:
1) if Kyma CR is under deletion, or 
2) user removed the module from Kyma CR 

Then LM will act the same, which means adding deletionTimestamp to module CR, right? If yes, I think it doesn't help.

What we want to achieve is the following, (two scenarios):
1) **User disables btp opertor module in the kyma resource**, then btp manager will check if any ServiceInstance(SI), ServiceBindings(SB) CRs exists. If yes, the user must delete them. When no single SI/SB then module CR is gone.
2) **KEB calls deletion on Kyma resource**. Then in this scenario btp manager removes ServiceInstance(SI), ServiceBindings(SB) on its own. It always will result in no SI/SB and then module CR is gone.

Please let me know how from your conclusions / recommendations we can implement that.

**Comment by pbochynski** [comment] 2023-03-14 08:12
@jakobmoellersap We need a way to free up resources quickly when when user decides to dispose cluster by deleting Kyma service instance through KEB. KEB will delete Kyma custom resource (managed by lifecycle manager) and when it is deleted will delete shoot resource. Unfortunately, if we do not clean up resources from the cluster shoot deletion will stuck (see: https://github.com/gardener/gardener/issues/3110). It is not acceptable to charge user for the cluster  that cannot be used therefore it is our cost. The issue is not about rsources created by module operators. It is about resources created by users using CRDs introduced by modules. These resources should not be deleted by the operator (user should delete them). The problem is that user instead of deleting all these resources decided to dispose entire cluster (or even deleted subaccount where cluster is created) and expects that all the resources created there will be soon gone. 
@PK85 proposed the strategy where you delegate such clean up to modules. But maybe it doesn't make sense as user can install some resources that are not related to any module and deletion can stuck anyway. So probably it would be better to activate forceful clean up anyway (after some timeout).

**Comment by janmedrek** [comment] 2023-03-15 10:43
We've decided to introduce another controller in the LM to force-remove all the resources and their finalizers from the cluster upon deletion (with a set timeout). **It should be later moved to the Infrastructure Operators.**

As for the modules we should still decide on the implementation, the options are Kubernetes-native way with orphan finalizers deletion or some sort of custom label-based logic.

Suggestion: modules should by default use the cascade delete, for the ones that would need to keep their children some sort of field/label could be introduced to prevent the user-created resources from being removed.

There would be two options for modules:
- force delete off: **default in the KCP scenario**, keep the resources and block the deletion until the customer removes all the children resources
- force delete on: remove all the children resources instantly

**Comment by janmedrek** [comment] 2023-03-15 10:52
Issues to be created:
- Implementation of the controller in the LM
- E2E test for the deletion scenario
- Introduce the modes for the module deletion
- Moving to the Infrastructure Operator

**Comment by janmedrek** [comment] 2023-03-16 08:34
Closing this issue in favour of the ones mentioned above

**Closed by janmedrek** 2023-03-16 08:34 UTC
Labels: kind/feature
